version: '3.4'

services:
  db:
    environment:
      - POSTGRES_PASSWORD
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app: &app_base
    image: terraform-rails
    build:
      context: .
      dockerfile: ./devops/docker/app/Dockerfile
      args:
        - ADDITIONAL_PACKAGES=nodejs-current yarn
        - EXECJS_RUNTIME=Node
        - RAILS_ENV=development
        - NODE_ENV=development
    environment: # this will override .env
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD
      - POSTGRES_USER=postgres
      - SECRET_KEY_BASE=abc123
      - RAILS_ENV=development
      - RAILS_MAX_THREADS
    links:
      - db
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids

  web:
    build:
      context: .
      dockerfile: ./devops/docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80

volumes:
  postgres_data:
    external: true
