# compose file specifically for docker-sync
version: '3.4'

services:
  app:
    volumes:
      - terraform-rails-app-sync:/app:nocopy
  worker:
    volumes:
      - terraform-rails-app-sync:/app:nocopy

volumes:
  terraform-rails-app-sync:
    external: true

